name: insight
version: "1.0.0"
config-version: 2
profile: insight

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  insight:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics
      +post-hook: "{{ tenant_rls() }}"